In [ ]:
import numpy as np

Basics

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2,3,4],[5,6,7,8]],dtype="int32")
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 4)

In [ ]:
b.dtype

dtype('int32')

In [ ]:
b.itemsize

4

In [ ]:
b.nbytes

32

accessing elements

In [ ]:
a=np.array([[1,2,35,8,56,87],[5,8,9,7,24,56]])
a

array([[ 1,  2, 35,  8, 56, 87],
       [ 5,  8,  9,  7, 24, 56]])

In [ ]:
a[0,2]

35

In [ ]:
a[0,:]

array([ 1,  2, 35,  8, 56, 87])

In [ ]:
a[:,2]

array([35,  9])

In [ ]:
a[0,:5:2]

array([ 1, 35, 56])

In [ ]:
a[0,2] = 3
a

array([[ 1,  2,  3,  8, 56, 87],
       [ 5,  8,  9,  7, 24, 56]])

In [ ]:
a[:,3] = [4,5]
a

array([[ 1,  2,  3,  4, 56, 87],
       [ 5,  8,  9,  5, 24, 56]])

In [ ]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
b[0,1,0]

3

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
b[:,0,:]=[[9,8],[9,7]]
b

array([[[9, 8],
        [3, 4]],

       [[9, 7],
        [7, 8]]])

types of array

In [ ]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [ ]:
np.random.rand(2,3)

array([[0.7998715 , 0.71500471, 0.81728767],
       [0.18618644, 0.87871671, 0.50871938]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.33141975, 0.08868851, 0.42685855, 0.4154247 , 0.58991359,
        0.32457504],
       [0.25733407, 0.66577   , 0.62643118, 0.33446568, 0.61987028,
        0.80728006]])

In [ ]:
np.random.randint(2,7,size=(3,3))

array([[4, 3, 6],
       [2, 4, 6],
       [2, 5, 4]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3]])
r= np.repeat(arr,3,axis=0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
mat = np.ones((5,5))
print(mat)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
mat[1:4,1:4] = z
print(mat)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3]) 
b = a.copy()
b[2]=50
print(a)
print(b)

[1 2 3]
[ 1  2 50]


math

In [ ]:
a= np.array([1,5,6])
b= np.array([5,5,8])
print(a * b)

[ 5 25 48]


In [ ]:
a ** 2

array([ 1, 25, 36])

In [ ]:
np.cos(a)

array([0.54030231, 0.28366219, 0.96017029])

In [ ]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),5)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]


array([[15., 15.],
       [15., 15.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
np.min(a)

1

In [ ]:
np.max(a, axis=1)

array([3, 6])

In [ ]:
np.sum(a)

21

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
b= a.reshape((3,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
v1= np.zeros(4,)
v2 = np.ones(4,)
np.vstack((v1,v2,v1))

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [ ]:
h1= np.zeros((2,4))
h2 = np.ones((2,2))
np.hstack((h1,h2))

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])