In [1]:
import numpy as np

In [5]:
def sigmoid(x):
    s=1/(1+np.exp(-x))
    return s


In [7]:
sigmoid(5)

0.9933071490757153

In [15]:
a=np.array([2,3,5])
print(sigmoid(a))

[0.88079708 0.95257413 0.99330715]


In [16]:
def sigmoid_grad(x):
    s=1./(1+np.exp(-x))
    ds=s*(1-s)
    return ds


In [17]:
a

array([2, 3, 5])

In [21]:
print("Derivative =" + str(sigmoid_grad(a)))

Derivative =[0.10499359 0.04517666 0.00664806]


In [22]:
def image2vector(x):
    

SyntaxError: unexpected EOF while parsing (<ipython-input-22-499b68bb6a3f>, line 2)

In [28]:
def normalize_rows(x):
    x_norm=np.linalg.norm(x,axis=0, keepdims=True)
    x=x/x_norm
    return x


In [37]:
x=np.array([[1,2],[3,2]])

In [38]:
x

array([[1, 2],
       [3, 2]])

In [39]:
normalize_rows(x)

array([[0.31622777, 0.70710678],
       [0.9486833 , 0.70710678]])

In [40]:
def softmax(x):
    x_exp=np.exp(x)
    x_sum=np.sum(x,axis=1, keepdims=True)
    s=x_exp/x_sum
    return s


In [43]:
x=np.array([[1,2,3,4,5],[2,5,6,7,4]])

In [44]:
x

array([[1, 2, 3, 4, 5],
       [2, 5, 6, 7, 4]])

In [45]:
softmax(x)

array([[ 0.18121879,  0.49260374,  1.33903579,  3.63987667,  9.89421061],
       [ 0.30787734,  6.18388163, 16.80953306, 45.69304827,  2.27492292]])

In [46]:
def loss(yhat,y):
    loss=np.sum(y-yhat)**2
    return loss


In [52]:
yhat=np.array([.1,.2,.3])
y=np.array([.5,.06,.7])
loss(yhat,y)

0.4355999999999999